---
- name: Configure packagecloud.io repository
  block:
    - name: Ensure dependencies are present.
      apt:
        name:
          - apt-transport-https
          - gnupg2
        state: present

    - name: Add packagecloud.io Varnish apt key.
      get_url:
        url: "https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey"
        dest: "/usr/share/keyrings/varnishcache_{{ varnish_packagecloud_repo }}-archive-keyring.asc"
        mode: 644
      # check_mode: false
      diff: true

    - name: Add packagecloud.io Varnish apt repository.
      apt_repository:
        repo: "{{ item }} [signed-by=/usr/share/keyrings/varnishcache_{{ varnish_packagecloud_repo }}-archive-keyring.asc] {{ varnish_apt_repo }}"
        filename: 'varnish-cache'
        state: present
      loop:
        - 'deb'
        - 'deb-src'
      # check_mode: false
      diff: true
  when: varnish_apt_use_packagecloud

- name: Ensure Varnish is installed.
  apt:
    name: "{{ varnish_package_name }}"
    state: present

- name: Ensure Varnish VMODs are installed.
  apt:
    name: "{{ varnish_modules_package_name }}"
    state: present
  when: varnish_modules_package_name
